services:
  agent-service:
    build:
      context: .
      args:
          APP_ENV: 'local'
    image: orbio/agent-service:local
    environment:
      ENVIRONMENT: 'local'
    ports:
      - "8001:8001"
    networks:
      - service-grp-net
      - agent-net
    command: python -m gunicorn -c ./agent/gunicorn_conf.py -k agent.uvicorn.UvicornWorker agent.asgi:application --reload
    user: "${UID}:${GID}"
    stdin_open: true
    tty: true
    env_file:
      - .env.local
    volumes:
      - ./:/opt/orbio/
      - ~/.ipython:/home/orbio/.ipython

  agent-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: orbio
      POSTGRES_PASSWORD: orbio
      POSTGRES_DB: orbio-db
    command: -c fsync=off
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - agent-net
    ports:
      - "5432:5432"

networks:
  agent-net: {}
  service-grp-net:
    external: true

volumes:
  pgdata: {}
