# Generated by Django 5.2 on 2025-05-02 16:50

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "function",
                    models.CharField(
                        choices=[
                            ("CUSTOMER_SUPPORT", "Customer Support"),
                            ("SCHEDULING", "Scheduling"),
                        ],
                        default="CUSTOMER_SUPPORT",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "bots",
            },
        ),
    ]
