# Generated by Django 5.2 on 2025-05-03 02:53

import agent.conversations.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bots", "0001_initial"),
        ("human_users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "raw_conversation",
                    models.JSONField(
                        default=agent.conversations.models.default_raw_conversation,
                        null=True,
                    ),
                ),
                (
                    "summary",
                    models.JSONField(
                        default=agent.conversations.models.default_summary, null=True
                    ),
                ),
                (
                    "bot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bots",
                        to="bots.bot",
                    ),
                ),
                (
                    "human_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="human_users",
                        to="human_users.humanuser",
                    ),
                ),
            ],
            options={
                "db_table": "conversations",
            },
        ),
    ]
