# Generated by Django 5.2 on 2025-06-08 17:07

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db.models import Func, F
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_opportunities", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS pg_trgm;"),
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS btree_gin;"),
        migrations.RunSQL(
            "CREATE OR REPLACE FUNCTION array_to_string_immutable(anyarray, text) "
            "RETURNS text "
            "AS $$ SELECT array_to_string($1, $2) $$ "
            "LANGUAGE SQL "
            "IMMUTABLE;"
        ),
        migrations.AlterField(
            model_name="jobopportunity",
            name="skills",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100), default=list, size=None
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX skills_idx "
                "ON job_opportunities "
                "USING gin (array_to_string_immutable(skills, ',') gin_trgm_ops);"
            ),
            reverse_sql="DROP INDEX IF EXISTS skills_idx;",
        ),
        migrations.AddIndex(
            model_name="jobopportunity",
            index=django.contrib.postgres.indexes.GinIndex(
                name="title_idx",
                fields=["title"],
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="jobopportunity",
            index=django.contrib.postgres.indexes.GinIndex(
                name="location_idx",
                fields=["location"],
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
